# Generated by Django 3.2.5 on 2021-07-08 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='作者'),
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(default='', verbose_name='正文'),
        ),
        migrations.AlterField(
            model_name='article',
            name='kind',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.article_kinds', verbose_name='分类'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(default='', max_length=50, verbose_name='标题'),
        ),
        migrations.AlterField(
            model_name='article_kinds',
            name='kinds',
            field=models.CharField(max_length=20, verbose_name='类别'),
        ),
    ]
